version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.11.4
    environment:
      GO111MODULE: on
    working_directory: /go/src/github.com/emojify-app/api
    steps:
      - checkout
      - run: go get -v -t -d ./...
      - run: go test -v ./...
